name: Waka Readme

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v4

      - name: WakaTime Readme Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          
          BLOCKS: █                  
          SHOW_TITLE: true           
          SHOW_TIME: true            
          SHOW_TOTAL: true           
          TIME_RANGE: last_7_days   
