name: Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: pedrodalmasdev
          base: habits
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          repositories_affiliations: owner
          config_timezone: America/Sao_Paulo
