name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity
          config_timezone: America/Sao_Paulo
          filename: github-metrics.svg

          # Plugins
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_followup: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
